### ISSUE TITLE
How do I call my FB accounts's inbox(conversations)?

### ISSUE THREAD

**Issue by o-kki** [raxod502/messyger#1]
Hello? I am trying to retrieve my FB conversation’s inbox using your API(messyger).
However, the value of ‘schema_version’ in line 57 of your code was empty.
I checked the schema_version’s value by debugging, I couldn’t find the value in ‘Inbox_html_page’. So, I could not retrieve ‘schemaVersion’ in line 90. Would you give me some advice on what I to do?  THX :D

**Comment by o-kki** [comment]
+ attachment
![image](https://user-images.githubusercontent.com/100291112/163768928-18a215f4-7f69-4273-8f71-87830ad73a34.png)

**Comment by raxod502** [comment]
Unfortunately, since the upstream API is always changing, projects like this are bound to go out of date. I've updated the README in https://github.com/raxod502/messyger/commit/486c95e1199dab48aeea46889b66c71c90deed4f to reflect this and give some suggestions about how to fix things (mostly, use [Unzuckify](https://github.com/raxod502/unzuckify) as an additional reference).

As a one-off, though, I took a quick look and indeed I can reproduce the error you're reporting here. I suspect it's the same issue I patched in https://github.com/raxod502/unzuckify/commit/fb9fb30755fecdfd588acb1b1c51a1de8b85e8de and [neighboring commits](https://github.com/raxod502/unzuckify/commits/main), so if you do the same I'm guessing you can get it working again. (I get alerted automatically whenever Unzuckify stops working, so I know that code is sound.)
